### PR TITLE
Making a great explanation even better

### PR DESCRIPTION
**Pull request by bruceLeeO**
Here's my contribution to making a great explanation even better :)

### CODE REVIEW

**Comment by bruceLeeO** [comment]
awesome..  great... I haven't got a pull request from purpose-readme-contribution?

**Comment by luisRojas29** [comment]
I'm seeing it in your main page of the fork in the tab of pull request...

**Comment by luisRojas29** [comment]
I already merge your pull request with my fork but i can't see any changes... maybe thats the issue everybody, well... not everybody is talking about ni the Q&A??

**Comment by bruceLeeO** [comment]
oh i see .... you need to fork my repository....  https://github.com/bruceLeeO/TrumpScript
then, git clone in your local machine... `$ git clone https://github.com/bruceLeeO/TrumpScript.git`
create a purpose-readme-contribution branch ... `$ git branch purpose-readme-contribution` 
switch branch... `git checkout purpose-readme-contribution`
open and edit the README.md file (make my great contribution even greater :))
then add it... `$ git add .`
then commit ... `$ git commit `
then push... `$ git push origin`
to set upstream branch for purpose-readme-contribution do this:
`$git push --set-upstream origin purpose-readme-contribution`

then you are ready to create pull request for the changes you made

**Comment by luisRojas29** [comment]
Ok, let me try here in work...

**Pull request merged**
