### PR TITLE
Add Part (b) assignment section in README

### PR DESCRIPTION
**Pull request by bruceLeeO**
ah sorry... I was caught up into reading about the Questions that I totally forgot about the pull request

### CODE REVIEW

**Comment by luisRojas29** [comment]
I think I request the pull on the wrong branch, I'll fix that... will you please send me the pull request to the non-developer-readme-contribution branch...

**Comment by bruceLeeO** [comment]
I think we are finally seeing the big picture :)

**Comment by luisRojas29** [comment]
try and failure but we got it... perseverance...

**Comment by bruceLeeO** [comment]
love that.... perseverance...

**Comment by luisRojas29** [comment]
could you please pull request me to the non-developer-readme-contribution branch??

**Comment by bruceLeeO** [comment]
I just did

**Pull request closed without merging**
